### ISSUE TITLE
Make the Back Button Real

### ISSUE THREAD

**Issue by cawlin** [evangillespie/monsterCards#10]
The back button should only take you from up a level. I have it hacked as a "browser back button" right now which is pretty wonky.

We have 2 levels right now so the back button should only appear on level 2.

1. List of Monsters
2. Monster Card

In the future we will have 3 levels so the back button should appear on level 2 and 3

1. List of Monster Card Decks
2. List of Monsters
3. Monster Card

**Comment by evangillespie** [comment]
I hacked the application template to do this. It's really not the best but it will work until we get other monster decks.
