### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by cawlin** [evangillespie/monsterCards#13]
An about page with:

* a simple paragraph
* our names (links to websites if anyone wants)
* a way to contact us for bugs
* a change log

**Comment by evangillespie** [comment]
I made the about page work and put some dummy content in there. Colin, can you style it up? I can write real content later. Waiting until I'm INSPIRED.

**Comment by cawlin** [comment]
HTML is better now - get inspired bro.

**Comment by evangillespie** [comment]
I edited the about page again. Also added a link to a new change log page. Going to edit one more time before closing this ticket.

**Comment by evangillespie** [comment]
Closing this ticket. Still need to update the feedback email on the page but we can't do that until we have a domain and email address.
