### ISSUE TITLE
Meta Descriptions

### ISSUE THREAD

**Issue by cawlin** [evangillespie/monsterCards#22]
We need meta descriptions for Google to be happier. Each page should have one!

For Monsters I think this would be good:

`<meta name="description" content="Stat block for [monster name] from [system]"/>`
Ex: Stat block for Goblin from D&D 5E SRD

@jonnyjohannes does rails have a way to pass a description for more unique pages like about, license etc.

**Comment by jonnyjohannes** [comment]
Yeah, we can have the meta tag dynamically created based on what page is loaded.

**Comment by cawlin** [comment]
Google likes our site structure. not going to worry about this.
