### ISSUE TITLE
Fix 404 errors

### ISSUE THREAD

**Issue by evangillespie** [evangillespie/monsterCards#25]
A bunch of monsters are producing 404 errors. Fix that.

> http://monstercards.ca/d&d5esrd/swarm-of-poisonous-snakes
> http://monstercards.ca/d&d5esrd/swarm-of-quippers
> http://monstercards.ca/d&d5esrd/swarm-of-rats
> http://monstercards.ca/d&d5esrd/swarm-of-wasps
> http://monstercards.ca/d&d5esrd/rug-of-smothering
> http://monstercards.ca/d&d5esrd/swarm-of-bats
> http://monstercards.ca/d&d5esrd/saber-toothed-tiger
> http://monstercards.ca/d&d5esrd/swarm-of-beetles
> http://monstercards.ca/d&d5esrd/swarm-of-ravens
> http://monstercards.ca/d&d5esrd/will-o'-wisp
> http://monstercards.ca/d&d5esrd/swarm-of-spiders
> http://monstercards.ca/d&d5esrd/half-red-dragon-veteran
> http://monstercards.ca/d&d5esrd/swarm-of-insects
> http://monstercards.ca/d&d5esrd/swarm-of-centipedes

**Comment by evangillespie** [comment]
It looks like the problem occurs for monsters with a '-' or 'of' in their name.

**Comment by jonnyjohannes** [comment]
The `titleize` and `gsub('-', ' ')` from the monster name in the url to matching it to the `Monster#name` is probably what's messing this up.

What we could do is: give every monster a unique `Monster#slug`. We should also index monsters on this attribute. This way we can do quick lookups on exact url-to-slug matches.
