### ISSUE TITLE
Add Empty/Error States

### ISSUE THREAD

**Issue by cawlin** [evangillespie/monsterCards#4]
Need some empty states. Preferably clever and "on brand"

* No Search Results
* No Filtered Results (list.js)
* 404 Error

**Comment by cawlin** [comment]
I have no idea how to implement these guys.

**Comment by cawlin** [comment]
I feel like you probably know exactly how to do this @jonnyjohannes

**Comment by cawlin** [comment]
@jonnyjohannes is there a way to have a "no results" message when a user types in a search and actually submits the form? For a url like `/?search=asfasf`

**Comment by jonnyjohannes** [comment]
@cawlin, sorry thought I had accommodated for this situation. The last push to `develop` has the live filter and the search form submit both using the dope skull thing you made.
