### ISSUE TITLE
Make search work from monster show

### ISSUE THREAD

**Issue by evangillespie** [evangillespie/monsterCards#6]
When you're looking at the stats for any monster, there is a a search bar at the top of the page that doesn't do anything. Make that work.

**Comment by cawlin** [comment]
I think we should just hide the search bar on this page!

**Comment by evangillespie** [comment]
I'm fine with that. How about you @jonnyjohannes ?

**Comment by jonnyjohannes** [comment]
That sounds good to me.

**Comment by cawlin** [comment]
cool dudes - I think the "D&D SRD 5e" should be a permalink to the "monster card deck" for that type. Imagining for when there could be more than one deck.\\

Mostly imagining the situation of landing on a specific monster from a shared link.

**Comment by evangillespie** [comment]
Removing the search bar closes this ticket. I'm closing it now.
