### ISSUE TITLE
Add SRD License

### ISSUE THREAD

**Issue by evangillespie** [evangillespie/monsterCards#7]
There is a link at the bottom of each monster that looks like it should link to the SRD license. Make that happen.

**Comment by cawlin** [comment]
Do you think a license link at the bottom of the monster list would be enough?

**Comment by evangillespie** [comment]
I think that could work.

**Comment by evangillespie** [comment]
I made an SRD licence page and put in some basic HTML. I couldn't figure out the css to make it look nice. There is a link to the page at the bottom of the monster list (link is also ugly)

@cawlin, can you pretty up the text and the link?

**Comment by cawlin** [comment]
I made the license and the license link look decent. Close if done @evangillespie
